#!/bin/bash
echo "Docker Login"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.heroku.com
echo "Docker Push"
docker push registry.heroku.com/scotlifestyle/web:latest
echo "Heroku Release"
heroku container:release web --app scotlifestyle
