import { fromJSOrdered } from './utils/immutable';

const SPORTS = {
    APP_NAME: 'SportsTalkSocial',
    APP_ICON: 'sports',
    APP_ICON_WIDTH: '50px',
    APP_ICON_HEIGHT: '40px',
    APP_URL: 'https://www.sportstalk.social',
    APP_DOMAIN: 'www.sportstalk.social',
    LIQUID_TOKEN: 'SPORTS',
    LIQUID_TOKEN_UPPERCASE: 'SPORTS',
    APP_MAX_TAG: 15,
    SCOT_TAG: 'sportstalk',
    TAG_LIST: fromJSOrdered({
        football: {
            tourneyplay: {
                afcon: ['afcon2019', 'afcon2021'],
                'american-cup': ['americancup2015', 'americancup2019'],
                copaamerica: ['copaamerica2019', 'copaamerica2020'],
                'euro-cup': ['eurocup2016', 'eurocup2020'],
                worldcup: ['worldcup2018', 'worldcup2022'],
                },
            leagueplay: {
                premierleague: [
                    'arsenal',
                    'astonvilla',
                    'bournemouth',
                    'brighton',
                    'burnley',
                    'chelsea',
                    'crystalpalace',
                    'everton',
                    'leicestercity',
                    'liverpool',
                    'manchestercity',
                    'manchesterunited',
                    'newcastleunited',
                    'norwichcity',
                    'sheffieldunited',
                    'southampton',
                    'tottenham',
                    'watford',
                    'westham',
                    'wolverhampton',
                    ],
                laliga: [
                    'alaves',
                    'athleticbilbao',
                    'atleticomadrid',
                    'barcelona',
                    'celtavigo',
                    'eibar',
                    'espanyol',
                    'getafe',
                    'granada',
                    'leganes',
                    'levante',
                    'mallorca',
                    'osasuna',
                    'realbetis',
                    'realmadrid',
                    'realsociedad',
                    'sevilla',
                    'valencia',
                    'valladolid',
                    'villarreal',
                ],
                mls: [
                    'atlantaunitedfc',
                    'chicagofire',
                    'fccincinnati',
                    'coloradorapids',
                    'columbuscrewsc',
                    'dcunited',
                    'fcdallas',
                    'houstondynamo',
                    'lagalaxy',
                    'lafc',
                    'minnesotaunitedfc',
                    'montrealimpact',
                    'newenglandrevolution',
                    'nycfc',
                    'nyredbulls',
                    'orlandocitysc',
                    'philadelphiaunion',
                    'portlandtimbers',
                    'realsaltlake',
                    'sanjoseearthquakes',
                    'seattlesoundersfc',
                    'sportingkansascity',
                    'torontofc',
                    'vancouverwhitecapsfc',
                ],
                npfl: [
                    'abiawarriors',
                    'adamawaunited',
                    'akwaunited',
                    'dakkadafc',
                    'enyimba',
                    'fcifeanyiubah',
                    'heartlandfc',
                    'jigawagoldenstars',
                    'kanopillarsfc',
                    'katsinaunited',
                    'kwaraunitedfc',
                    'lobistarsfc',
                    'mfmfc',
                    'nasarawaunitedfc',
                    'plateauunited',
                    'rangersintl',
                    'riversunited',
                    'sunshinestarsfc',
                    'warriwolvesfc',
                    'wikkitouristfc',
                ],
                ligue1: [
                    'angers',
                    'bordeaux',
                    'brest',
                    'dijon',
                    'lens',
                    'lille',
                    'lorient',
                    'lyon',
                    'marseille',
                    'metz',
                    'monaco',
                    'montpellier',
                    'nantes',
                    'nice',
                    'nimes',
                    'psg',
                    'reims',
                    'rennes',
                    'asse',
                    'strasbourg',
                ],
        },
    },
    americanfootball: {
        nfl: {
            afc: [
                'bengals',
                'bills',
                'broncos',
                'browns',
                'chargers',
                'chiefs',
                'chargers',
                'colts',
                'dolphins',
                'jaguars',
                'jets',
                'patriots',
                'raiders',
                'steelers',
                'texans',
                'titans',
            ],
            nfc: [
                '49ers',
                'bears',
                'buccaneers',
                'cardinals',
                'cowboys',
                'cowboys',
                'eagles',
                'falcons',
                'giants',
                'lions',
                'packers',
                'panthers',
                'rams',
                'redskins',
                'seahawks',
                'vikings',
            ],
        },
        ncaafb: {
            accfb: [
                'bostoncollegefb',
                'clemsonfb',
                'dukefb',
                'fsufb',
                'georigatechfb',
                'louisvillefb',
                'miamifb',
                'ncstatefb',
                'uncfb',
                'notredamefb',
                'pittsburghfb',
                'syracusefb',
                'virginiafb',
                'virginiatechfb',
                'wakeforestfb',
            ],
            bigtenfb: [
                'illinoisfb',
                'indianafb',
                'iowafb',
                'marylandfb',
                'michiganfb',
                'michiganstatefb',
                'minnesotafb',
                'nebraskafb',
                'northwesternfb',
                'ohiostatefb',
                'pennstatefb',
                'purduefb',
                'rutgersfb',
                'wisconsinfb',
            ],
            big12fb: [
                'baylorfb',
                'iowastatefb',
                'kansasfb',
                'kansasstatefb',
                'oklahomafb',
                'oklahomastatefb',
                'tcufb',
                'texasfb',
                'texastechfb',
                'westvirginiafb',
            ],
            pac12fb: [
                'arizonafb',
                'asufb',
                'californiafb',
                'coloradofb',
                'oregonfb',
                'oregonstatefb',
                'standfordfb',
                'uclafb',
                'uscfb',
                'utahfb',
                'washingtonfb',
                'washingtonstatefb',
            ],
            secfb: [
                'alabamafb',
                'arkansasfb',
                'auburnfb',
                'floridafb',
                'georgiafb',
                'kentuckyfb',
                'lsufb',
                'mississippistatefb',
                'missourifb',
                'olemissfb',
                'southcarolinafb',
                'tennesseefb',
                'texasamfb',
                'vanderbiltfb',
            ],
        },
    },
    baseball: {
        mlb: {
            americanleague: [
                'angels',
                'astros',
                'athletics',
                'bluejays',
                'indians',
                'mariners',
                'orioles',
                'rangers',
                'rays',
                'redsox',
                'royals',
                'tigers',
                'twins',
                'whitesox',
                'yankees',
            ],
            nationalleague: [
                'braves',
                'brewers',
                'cardinals',
                'cubs',
                'diamondbacks',
                'dodgers',
                'giants',
                'marlins',
                'mets',
                'nationals',
                'padres',
                'phillies',
                'pirates',
                'reds',
                'rockies',
                ],
            },
        alpb: {
            alpbnorth: [
                'lancasterbarnstormers',
                'longislandducks',
                'southernmarylandbluecrabs',
                'yorkrevolution',
            ],
            alpbsouth: [
                'gastoniahoneyhunters',
                'highpointrockers',
                'lexingtonlegends',
                'westvirginiapower',
            ],
        },
        ncaabaseball: {
            accbb: [
                'bostoncollegebb',
                'clemsonbb',
                'dukebb',
                'fsubb',
                'georigatechbb',
                'louisvillebb',
                'miamibb',
                'ncstatebb',
                'uncbb',
                'notredamebb',
                'pittsburghbb',
                'syracusebb',
                'virginiabb',
                'virginiatechbb',
                'wakeforestbb',
            ],
            bigtenbb: [
                'illinoisbb',
                'indianabb',
                'iowabb',
                'marylandbb',
                'michiganbb',
                'michiganstatebb',
                'minnesotabb',
                'nebraskabb',
                'northwesternbb',
                'ohiostatebb',
                'pennstatebb',
                'purduebb',
                'rutgersbb',
                'wisconsinbb',
            ],
            big12bb: [
                'baylorbb',
                'iowastatebb',
                'kansasbb',
                'kansasstatebb',
                'oklahomabb',
                'oklahomastatebb',
                'tcubb',
                'texasbb',
                'texastechbb',
                'westvirginiabb',
            ],
            pac12bb: [
                'arizonabb',
                'asubb',
                'californiabb',
                'coloradobb',
                'oregonbb',
                'oregonstatebb',
                'standfordbb',
                'uclabb',
                'uscbb',
                'utahbb',
                'washingtonbb',
                'washingtonstatebb',
            ],
            secbb: [
                'alabamabb',
                'arkansasbb',
                'auburnbb',
                'floridabb',
                'georgiabb',
                'kentuckybb',
                'lsubb',
                'mississippistatebb',
                'missouribb',
                'olemissbb',
                'southcarolinabb',
                'tennesseebb',
                'texasambb',
                'vanderbiltbb',
            ],
        },
    },
    basketball: {
        nba: {
            eastern: [
                'hawks',
                'celtics',
                'nets',
                'hornets',
                'bulls',
                'cavaliers',
                'pistons',
                'pacers',
                'heat',
                'bucks',
                'knicks',
                'magic',
                '76ers',
                'raptors',
                'wizards',
            ],
            western: [
                'mavericks',
                'nuggets',
                'warriors',
                'rockets',
                'clippers',
                'lakers',
                'grizzlies',
                'timberwolves',
                'pelicans',
                'thunder',
                'suns',
                'trailblazers',
                'kings',
                'spurs',
                'jazz',
            ],
        },
        ncaamb: {
            accmb: [
                'bostoncollegemb',
                'clemsonmb',
                'dukemb',
                'fsumb',
                'georigatechmb',
                'louisvillemb',
                'miamimb',
                'ncstatemb',
                'uncmb',
                'notredamemb',
                'pittsburghmb',
                'syracusemb',
                'virginiamb',
                'virginiatechmb',
                'wakeforestmb',
            ],
            bigtenmb: [
                'illinoismb',
                'indianamb',
                'iowamb',
                'marylandmb',
                'michiganmb',
                'michiganstatemb',
                'minnesotamb',
                'nebraskamb',
                'northwesternmb',
                'ohiostatemb',
                'pennstatemb',
                'purduemb',
                'rutgersmb',
                'wisconsinmb',
            ],
            big12mb: [
                'baylormb',
                'iowastatemb',
                'kansasmb',
                'kansasstatemb',
                'oklahomamb',
                'oklahomastatemb',
                'tcumb',
                'texasmb',
                'texastechmb',
                'westvirginiamb',
            ],
            pac12mb: [
                'arizonamb',
                'asumb',
                'californiamb',
                'coloradomb',
                'oregonmb',
                'oregonstatemb',
                'standfordmb',
                'uclamb',
                'uscmb',
                'utahmb',
                'washingtonmb',
                'washingtonstatemb',
            ],
            secmb: [
                'alabamamb',
                'arkansasmb',
                'auburnmb',
                'floridamb',
                'georgiamb',
                'kentuckymb',
                'lsumb',
                'mississippistatemb',
                'missourimb',
                'olemissmb',
                'southcarolinamb',
                'tennesseemb',
                'texasammb',
                'vanderbiltmb',
            ],
        },
    },
    hockey: {
        nhl: {
            nhleastern: [
                'bostonbruins',
                'buffalosabres',
                'carolinahurricanes',
                'columbusbluejackets',
                'detroitredwings',
                'floridapanthers',
                'montrealcanadiens',
                'newjerseydevils',
                'newyorkislanders',
                'newyorkrangers',
                'ottawasenators',
                'philadelphiaflyers',
                'pttsburghpenguins',
                'tampabaylightning',
                'torontomapleleafs',
                'washingtoncapitals',
            ],
            nhlwestern: [
                'anaheimducks',
                'arizonacoyotes',
                'calgaryflames',
                'chicagoblackhawks',
                'coloradoavalanche',
                'dallasstars',
                'edmontonoilers',
                'losangeleskings',
                'minnesotawild',
                'nashvillepredators',
                'saintlouisblues',
                'sanjosesharks',
                'vancouvercanucks',
                'vegasgoldenknights',
                'winnipegjets',
            ],
        },
    },
    mma: ['ufc'],
    olympics: {
        olympicfootball: [],
        archery: [],
        athletics: [],
        badminton: [],
        olympicbaseball: [],
        softball: [],
        olympicbasketball: ['3x3basketball'],
        volleyball: ['beachvolleyball'],
        boxing: [],
        watersports: [
            'canoeslalom',
            'canoesprint',
            'waterpolo',
            'diving',
            'rowing',
            'sailing',
            'surfing',
            'swimming',
            'marathonswimming',
            'artisticswimming',
        ],
        olympiccycling: [
            'bmxfreestyle',
            'bmxracing',
            'mountainbike',
            'roadcycling',
            'trackcycling',
        ],
        equestrian: [],
        fencing: [],
        olympicgolf: [],
        gymnastics: ['artisticgymnastics', 'rhythmicgymnastics', 'trampolinegymnastics'],
        handball: [],
        olympichockey: [],
        judo: [],
        karate: [],
        modernpentathlon: [],
        rugby: [],
        shooting: [],
        skateboarding: [],
        sportclimbing: [],
        tabletennis: [],
        olympictennis: [],
        triathlon: [],
        weightlifting: [],
        wrestling: [],
    },
    sports: {
        cricket: [],
        golf: [
            'masters',
            'usopenchampionship',
            'britishopen',
            'pgachampionship',
        ],
        tennis: ['wimbledon', 'usopen', 'australianopen', 'frenchopen'],
        prowrestling: ['wwe', 'aew', 'njpw', 'roh'],
        lacrosse: [],
        kabaddi: [],
        billards: ['pool', 'snooker'],
        cycling: ['giroditalia', 'tourdefrance', 'lavuelta'],
        motorsports: ['nascar', 'indycar', 'nhra', 'formulaone', 'motocross'],
        horseracing: [
            'breederscup',
            'kentuckyderby',
            'preaknessstakes',
            'belmontstakes',
            'kentuckyoaks',
            'pegasusworldcup',
        ],
        competitionsports: [
            'dance',
            'cheer',
            'figureskating',
        ],
        mentalsports: [
            'chess',
            'poker',
            'go',
            'backgammon',
            'draughts',
            'mahjong',
        ],
        discsports: ['discgolf', 'ultimatefrisbee'],
        extremesports: [
            'bmx',
            'snowboarding',
            'skiing',
            'rollerskating',
            'lugeing',
            'rockclimbing',
            'skydiving',
            'rodeo',
        ],
        bowling: [],
        outdoors: ['fishing', 'hunting', 'kayaking'],
        esports: [
            'fortniteworldcup',
            'leagueworldchampionship',
            'theinternational',
            'cwl',
            'overwatchleague',
            'haloworldchampionship',
            'pubgglobalchampionship',
            'dota2asiachampionships',
        ],
    },
    fantasy: [
        'fantasypremierleague',
        'sfpl',
        'fantasybaseball',
        'fantasybasketball',
        'fantasyfootball',
    ],
    sportsgov: [
        'sportsproposals',
        'sportspetitions',
    ],
    'hive-engine': {
        actifit: [],
        tribes: [
            'archon',
            'ash',
            'ctp',
            'dunk',
            'leofinance',
            'neoxian',
            'palnet',
            'pob',
            ],
        },
    }),
    INTERLEAVE_PROMOTED: true,
    PROMOTED_POST_ACCOUNT: 'null',
    VESTING_TOKEN: 'SPORTS POWER',
    SITE_DESCRIPTION:
        'SportsTalkSocial is a sports focused social media platform where everyone gets paid for ' +
        'creating and curating content. It leverages a robust digital points system, called SPORTS, that ' +
        'supports real value for digital rewards through market price discovery and liquidity',
    // Revive Ads
    NO_ADS_STAKE_THRESHOLD: 50000000000,
    REVIVE_ADS: {
      header_banner: {
          zoneId: '1848',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
      sidebar_left: {
          zoneId: '1849',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
      sidebar_right: {
          zoneId: '1850',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
      post_footer_abovecomments: {
          zoneId: '1851',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
      post_footer_betweencomments: {
          zoneId: '1852',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
      feed: {
          zoneId: '1847',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
      feed_small: {
          zoneId: '1903',
          reviveId: '727bec5e09208690b050ccfc6a45d384',
      },
    },
    ALLOW_MASTER_PW: false,
    // Footer to attach to posts. ${POST_URL} is a macro that can be used, will be expanded to the URL of the post.
    POST_FOOTER: '',
    COMMENT_FOOTER: '',
    SCOT_TAG_FIRST: false,
    SDC_GTAG_MEASUREMENT_ID: 'G-LHBWFW0JD5',
    DISABLE_STEEM: true,
    PREFER_HIVE: true,
    HIVE_ENGINE: true,
    HIVE_ENGINE_SMT: 9,
    POSTED_VIA_NITROUS_ICON: 'sportstalk',
    COMMUNITY_CATEGORY: 'hive-101690',
    CHAT_CONVERSATIONS: [
        { id: '01EYM90246AEWTX8A4HYABXG6G', name: 'SportsTalkSocial Main Chat' },
        { id: '01EPB6A2PPSW0BQVJ7WDDP568C', name: 'BeeChat Trollbox' },
    ],
    SHOW_TOKEN_STATS: true,
    TWITTER_HANDLE: '@SportsTalkHive',
};

export const CONFIG_MAP = {
    // testing heroku/local options
    'localhost:8080': SPORTS,
    'www.sportstalk.social': SPORTS,
};

export const HIVE_SIGNER_APP = 'ewd';

export const CURRENCY_SIGN = '$';
export const WIKI_URL = ''; // https://wiki.golos.io/

// these are dealing with asset types, not displaying to client, rather sending data over websocket
export const LIQUID_TICKER = 'HIVE';
export const VEST_TICKER = 'VESTS';

// application settings
export const DEFAULT_LANGUAGE = 'en'; // used on application internationalization bootstrap
export const DEFAULT_CURRENCY = 'USD';
export const ALLOWED_CURRENCIES = ['USD'];

export const TOKEN_STATS_EXCLUDE_ACCOUNTS = [
    'sportsprojects',
    'sports-gov',
];

export const HIVE_ENGINE = true;
export const LIQUID_TOKEN_UPPERCASE = 'SPORTS';

