const map = {
    //steemit
    ned: 'steemit',
    justinw: 'steemit',
    elipowell: 'steemit',
    vandeberg: 'steemit',
    birdinc: 'steemit',
    gerbino: 'steemit',
    andrarchy: 'steemit',
    roadscape: 'steemit',
    steemitblog: 'steemit',
    steemitdev: 'steemit',

    //cerified uloggwr
    surpassinggoogle: 'certified_ulogger',
    yos.dikuta: 'certified_ulogger',
    aaronli: 'certified_ulogger',
    nuagnorab: 'certified_ulogger',
    hertz300: 'certified_ulogger',
    honoru: 'certified_ulogger',
    fatherfaith: 'certified_ulogger',
    felt.buzz: 'certified_ulogger',
    darthnava: 'certified_ulogger',
    syllem: 'certified_ulogger',
    sammiegold: 'certified_ulogger',
    dimsyto: 'certified_ulogger',
    julstamban: 'certified_ulogger',
    eddie23: 'certified_ulogger',
    iyanpol12: 'certified_ulogger',
    heeyahnuh: 'certified_ulogger',
    stevenmosoes: 'certified_ulogger',
    hassanabid: 'certified_ulogger',
    ilukzymoore: 'certified_ulogger',
    mosunomotunde: 'certified_ulogger',
    kolkamkwan: 'certified_ulogger',
    equipodelta: 'certified_ulogger',
    allerie00: 'certified_ulogger',
    dee-y: 'certified_ulogger',
    dennisdaniel: 'certified_ulogger',
    imbigdee: 'certified_ulogger',
    prechyrukky: 'certified_ulogger',
    afterglow: 'certified_ulogger',
    tezzmax: 'certified_ulogger',
    ammyluv: 'certified_ulogger',
    sgbonus: 'certified_ulogger',
    olawalium: 'certified_ulogger',
    oredebby: 'certified_ulogger',
    dtwo: 'certified_ulogger',
    zyzymena: 'certified_ulogger',
    bozz: 'certified_ulogger',
    goldendawne: 'certified_ulogger',
    davomaster: 'certified_ulogger',
    ayoshewa: 'certified_ulogger',
    tieulongdl711: 'certified_ulogger',
    lebey1: 'certified_ulogger',
    promzyelisha: 'certified_ulogger',
    emekasegun: 'certified_ulogger',
    julietisrael: 'certified_ulogger',
    fionasfavourites: 'certified_ulogger',
    blueeyes8960: 'certified_ulogger',
    mayb: 'certified_ulogger',
    uyobong: 'certified_ulogger',
    edeejosh: 'certified_ulogger',
    factism: 'certified_ulogger',
    anikys3reasure: 'certified_ulogger',
};

export default map;
