const map = {
    //steemit
    ned: 'Steemit',
    justinw: 'Steemit',
    elipowell: 'Steemit',
    vandeberg: 'Steemit',
    birdinc: 'Steemit',
    gerbino: 'Steemit',
    andrarchy: 'Steemit',
    roadscape: 'Steemit',
    steemitblog: 'Steemit',
    steemitdev: 'Steemit',

    // Add Custom Badges. Use single quotes for the key if user has . or -,  e.g.
    // 'robot.pay' : 'Robot',

    // Verified Creator
    thescarletletter: 'Verified Creator',
    discostick: 'Verified Creator',
    o0pepper0o: 'Verified Creator',
    davescustommedia: 'Verified Creator',
    ashyeyecandy: 'Verified Creator',
    hotnimmi: 'Verified Creator',
    futuremind: 'Verified Creator',
    reneeblack: 'Verified Creator',
    akiroq: 'Verified Creator',
    grdygoddessmegan: 'Verified Creator',
    lydialovely: 'Verified Creator',
    lenarose: 'Verified Creator',
    sexonlegs: 'Verified Creator',
    daddycosmic: 'Verified Creator',
    natashyamonroe: 'Verified Creator',
    awkwardness: 'Verified Creator',
    daiel: 'Verified Creator',
    'ebony-hot': 'Verified Creator',
    'soft-touch': 'Verified Creator',
    radnerd26: 'Verified Creator',
    'porn.blog': 'Verified Creator',
    'lady-o': 'Verified Creator',
    'joey-fancy': 'Verified Creator',
    'queen-of-heart': 'Verified Creator',
    speciallkay: 'Verified Creator',
    'petite-love': 'Verified Creator',
    bitfook: 'Verified Creator',
    'please-daddy': 'Verified Creator',
    'dark-queen': 'Verified Creator',
    kinkytales: 'Verified Creator',
    queencity: 'Verified Creator',
    littlemii: 'Verified Creator',
    nspart: 'Verified Creator',
    malefica: 'Verified Creator',
    thaiprincess: 'Verified Creator',
    kooklaskock: 'Verified Creator',
    babporn: 'Verified Creator',
    rapunzzel: 'Verified Creator',
    hiddenblade: 'Verified Creator',
    ebonysex: 'Verified Creator',
    shind: 'Verified Creator',
    'shamy.ver': 'Verified Creator',
    eveuncovered: 'Verified Creator',
    axeman: 'Verified Creator',
    'cimaron.passion': 'Verified Creator',
    oldviking: 'Verified Creator',
    jullyette:   'Verified Creator',
  
    
};

export default map;
