const map = {
    //steemit
    ned: 'Steemit',
    justinw: 'Steemit',
    elipowell: 'Steemit',
    vandeberg: 'Steemit',
    birdinc: 'Steemit',
    gerbino: 'Steemit',
    andrarchy: 'Steemit',
    roadscape: 'Steemit',
    steemitblog: 'Steemit',
    steemitdev: 'Steemit',

    // Add Custom Badges. Use single quotes for the key if user has . or -,  e.g.
    // 'robot.pay' : 'Robot',

    //naturl
    naturalcuration: 'NaturalProducts Team',
    nonatrl4u: 'NaturalProducts Team',
    naturalproducts: 'NaturalProducts Team',
    naturalbounties: 'NaturalProducts Team',
    natrlvoter: 'NaturalProducts Team',
    naturalpromo: 'NaturalProducts Team',
    jasonbu: 'NaturalProducts Editor',
    lmon: 'NaturalProducts Editor',
    liambu: 'NaturalProducts Curator',
    anggreklestari: 'NaturalProducts Curator',
    'bahagia-arbi': 'NaturalProducts Curator',
    balte: 'NaturalProducts Patron',
    ttg: 'NaturalProducts Patron',
    alokkumar121: 'NaturalProducts Delegator',
    amar15: 'NaturalProducts Delegator',
    amico: 'NaturalProducts Delegator',
    anttn: 'NaturalProducts Delegator',
    artemislives: 'NaturalProducts Delegator',
    certain: 'NaturalProducts Delegator',
    conradsuperb: 'NaturalProducts Delegator',
    dotwin1981: 'NaturalProducts Delegator',
    edkarnie: 'NaturalProducts Delegator',
    fleur: 'NaturalProducts Delegator',
    hafizullah: 'NaturalProducts Delegator',
    hatoto: 'NaturalProducts Delegator',
    jznsamuel: 'NaturalProducts Delegator',
    liucixin: 'NaturalProducts Delegator',
    mystry360: 'NaturalProducts Delegator',
    'pet.society': 'NaturalProducts Delegator',
    reeta0119: 'NaturalProducts Delegator',
    sumit71428: 'NaturalProducts Delegator',
    'super-irie': 'NaturalProducts Delegator',
    tixinhacapitinha: 'NaturalProducts Delegator',
    travelgirl: 'NaturalProducts Delegator',
    trayan: 'NaturalProducts Delegator'
};

export default map;
