const map = {
    // default
    '':
        "Our communities are overseen by *'certified uloggers'* only. Get *'certified'* **[here](https://www.marlians.com/marlians/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available)**`; then, indicate your interest in overseeing a community by contacting '@surpassinggoogle#1660' on [discord](https://discord.gg/nHVV5e9)",

    ulog:
        "All forms of content, spanning over every niche allowed here, as long as all aspects of the content like text, videos, images, graphics etc was created 'fresh' and entirely by U, without resourcing from the internet. For help, contact these 'certified' uloggers; [@snook](https://www.marlians.com/@snook), [@surpassinggoogle](https://www.marlians.com/@surpassinggoogle), [@dreemsteem](https://www.marlians.com/@dreemsteem) or [@anikys3reasure](https://www.marlians.com/@anikys3reasure) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    mamaput:
        "Share your canteen or 'street food' moments. Use these moments to exercise and explore more aspects of your human sense. Then, shine this beauty forth in a post. For help, contact these 'certified' uloggers; [@surpassinggoogle](https://www.marlians.com/@surpassinggoogle), [@sgbonus](https://www.marlians.com/@sgbonus) or [@imbigdee](https://www.marlians.com/@imbigdee) **[here!](https://discord.gg/nHVV5e9)**",
    steemjet:
        "Celebrate your [@dimimp](https://www.marlians.com/@dimimp) moments. Shine forth '[SteemJet](https://ulogs.org/@steemjet)' like it should have be shone forth. Be 'confirm naijan'. Relegate reservations, exercise your talents. For help, contact these 'certified' uloggers; [@surpassinggoogle](https://www.marlians.com/@surpassinggoogle), [@lordjames](https://www.marlians.com/@lordjames) or [@uche-nna](https://www.marlians.com/@uche-nna) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    'utopian-io':
        "[#utopian-io](https://www.marlians.com/created/utopian-io) has been a gift. We would like to keep its curation-efforts alive here on 'marlians.com'. We want to curate and reward 'contributions to open-source projects' with [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS); this can include suggestions, graphics, bug-finds, code etc.  Check out [#macrohard](https://www.marlians.com/created/macrohard), especially if you are not an expert-contributor. For help, contact these 'certified' uloggers; [@tobias-g](https://www.marlians.com/@tobias-g), [cadawg](https://www.marlians.com/@cadawg), [eastmael](https://www.marlians.com/@eastmael) or [quochuy](https://www.marlians.com/@quochuy) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    creativecoin:
        "Why not earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) along with your [CREATIVECOIN](https://steem-engine.com/?p=market&t=CCC) on your 'creative instances'. Marlians.com celebrates 'activities' that 'mine the human'. You now have more reasons to exert your '5 senses'; graphics, writings, drawings, photography etc. For help, contact these 'certified' uloggers; [@derangedvisions](https://www.marlians.com/@derangedvisions) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    steemitmamas:
        "Where are the mums at? Much isn't documented about the beauty & shine of our precious 'mamas'; about 'this woman's work'. Let's document these ulogacies and fix generations. Let's take 'lights' from this particular breed of 'shine', even into tunnels. Share each 'mama moment'; kids, joys, tears and all. Earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) too! Consider adding in '#ulog' & '#ulog-mamas' to enhance our curation capabilities. For help, contact these 'certified' uloggers; [@metzli](https://www.marlians.com/@metzli) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
};

export default map;
