const map = {
    // default
    '':
        "Our communities are overseen by *'certified uloggers'* only. Get *'certified'* **[here](https://www.marlians.com/marlians/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available)**`; then, indicate your interest in overseeing a community by contacting '@surpassinggoogle#1660' on [discord](https://discord.gg/nHVV5e9)",

    ulog:
        "All forms of content, spanning over every niche allowed here, as long as all aspects of the content like text, videos, images, graphics etc was created 'fresh' and entirely by U, without resourcing from the internet. For help, contact these 'certified' uloggers; [@snook](https://www.marlians.com/@snook), [@surpassinggoogle](https://www.marlians.com/@surpassinggoogle), [@dreemsteem](https://www.marlians.com/@dreemsteem) or [@anikys3reasure](https://www.marlians.com/@anikys3reasure) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    mamaput:
        "Share your canteen or 'street food' moments. Use these moments to exercise and explore more aspects of your human sense. Then, shine this beauty forth in a post. For help, contact these 'certified' uloggers; [@surpassinggoogle](https://www.marlians.com/@surpassinggoogle), [@sgbonus](https://www.marlians.com/@sgbonus) or [@imbigdee](https://www.marlians.com/@imbigdee) **[here!](https://discord.gg/nHVV5e9)**",
    steemjet:
        "Celebrate your [@dimimp](https://www.marlians.com/@dimimp) moments. Shine forth '[SteemJet](https://ulogs.org/@steemjet)' like it should have be shone forth. Be 'confirm naijan'. Relegate reservations, exercise your talents. For help, contact these 'certified' uloggers; [@surpassinggoogle](https://www.marlians.com/@surpassinggoogle), [@lordjames](https://www.marlians.com/@lordjames) or [@uche-nna](https://www.marlians.com/@uche-nna) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    'utopian-io':
        "[#utopian-io](https://www.marlians.com/created/utopian-io) has been a gift. We would like to keep its curation-efforts alive here on 'marlians.com'. We want to curate and reward 'contributions to open-source projects' with [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS); this can include suggestions, graphics, bug-finds, code etc.  Check out [#macrohard](https://www.marlians.com/created/macrohard), especially if you are not an expert-contributor. For help, contact these 'certified' uloggers; [@tobias-g](https://www.marlians.com/@tobias-g), [cadawg](https://www.marlians.com/@cadawg), [eastmael](https://www.marlians.com/@eastmael) or [quochuy](https://www.marlians.com/@quochuy) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    creativecoin:
        "Why not earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) along with your [CREATIVECOIN](https://steem-engine.com/?p=market&t=CCC) on your 'creative instances'. Marlians.com celebrates 'activities' that 'mine the human'. You now have more reasons to exert your '5 senses'; graphics, writings, drawings, photography etc. For help, contact these 'certified' uloggers; [@derangedvisions](https://www.marlians.com/@derangedvisions), [@dreemit](https://www.marlians.com/@dreemit) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    steemitmamas:
        "Where are the mums at? Much isn't documented about the beauty & shine of our precious 'mamas'; about 'this woman's work'. Let's document these ulogacies and fix generations. Let's take 'lights' from this particular breed of 'shine', even into tunnels. Share each 'mama moment'; kids, joys, tears and all. Earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) too! Consider adding in '#ulog' & '#ulog-mamas' to enhance our curation capabilities. For help, contact these 'certified' uloggers; [@metzli](https://www.marlians.com/@metzli), [@kobold-djawa](https://www.marlians.com/@kobold-djawa) or [@iamjadeline](https://www.marlians.com/@iamjadeline) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    cn:
        "Marlians.com is about 'returning value to humans'. Nations are simply 'locations'. We are creating a home and we want [#cn](https://www.marlians.com/created/cn) on 'marlians.com' to constitute a home too; emanating 'real human growth' and generation-fixers. Let's grow together. Let's move together. That's the real move! We welcome the entire [#cn](https://www.marlians.com/created/cn). You can earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) too! For help, contact these 'certified' uloggers; [@htliao](https://www.marlians.com/@htliao), [@minloulou](https://www.marlians.com/@minloulou) or [@cn-marlians](https://www.marlians.com/@cn-marlians) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    sportstalk:
        "Why not earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) too, for your 'sports talk'. It's called 'sportstalk' though, so why not exert some of your senses, 'mine your human' a bit and really sports-talk. Share everything sports-related. Earn [SPORTS](https://steem-engine.com/?p=market&t=SPORTS) and [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) too! We have staked some 'SPORTS' to enable you shine some more, through 'sports'. Do well to add your resources in and spend time on 'marlians.com' to curate [#sportstalk](https://www.marlians.com/created/sportstalk). Let's move together! For help, contact these 'certified' uloggers; [@uwelang](https://www.marlians.com/@uwelang), [@abh12345](https://www.marlians.com/@abh12345) or [patrickulrich](https://www.marlians.com/@patrickulrich) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    homesteading:
        "You now have one more reason to share your homesteading moments. Well, 'two'. By its means, you can 'mine your human' some more and can earn [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) in turn. There is 'home' on marlians.com for homesteaders now. Where you can't publish a post, do well to add your resources in and spend time on 'marlians.com' to curate #homesteading. Let's move together! For help, contact these 'certified' uloggers; [@papa-pepper](https://www.marlians.com/@papa-pepper), [@quochuy](https://www.marlians.com/@quochuy) **[here!](https://discord.gg/nHVV5e9)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available).",
    mermaidvampire:
        "This is special tag on marlians.com and an entire'home'. A place whereupon you can feel empowered, be inspired, grow and transmit power. It's for you 'steemheads', 'planktons' and for each one who is 'whale' inside. It is time to 'really move' and [@mermaidvampire](https://marlians.com/@mermaidvampire) leads the way. Document 'each step' in a post, curate others who 'document their steps', support them with the [PLANKTON](https://steem-engine.com/?p=market&t=PLKN) token and earn some [MARLIANS](https://steem-engine.com/?p=market&t=MARLIANS) too. For help, contact these 'certified' uloggers; [@mermaidvampire](https://www.marlians.com/@mermaidvampire) or [@cadawg](https://www.marlians.com/@cadawg) **[here!](https://discord.gg/D7t72fM)** You too can oversee a community. Get 'certified' by completing [these 4 simple-steps](https://www.marlians.com/@surpassinggoogle/simplified-process-for-becoming-a-certified-ulogger-now-4-very-simple-steps-only-chinese-and-korean-translation-available). For inquiries, join this [discord](https://discord.gg/nHVV5e9)",
};

export default map;
